#!/bin/bash

echo "Welcome to CISC220 Racing Arena"
read -p  "Enter the number of player and press [ENTER]:" numPlayer
echo "User press your number to move forward"

for ((i=0; i<$numPlayer; i++)); do
    var[$i]="|->                                        #  Lane $((i+1)) #"
    echo "${var[i]}"
done
while true;do
read -n1 userInput
clear
pat=$((userInput-1))
replace="~|->"
for line in "${var[@]}"; do
res="${line//[^~0]}"
occurence="${#res}"
if (($occurence==40));then
	echo "Player$userInput wins" && break 2
else
	if
		[[ "$line" = *$userInput* ]];then
		var[$pat]="${line/|-> /$replace}"
		echo "${var[$pat]}"
	else
		echo "$line"
	fi

fi
done
done          
